name: citibike_rides_hourly_features_pipeline

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch: {}

jobs:
  run-feature-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_feature_pipeline.txt

      - name: Debug working directory and verify file structure
        run: |
          echo "== Working Directory =="
          pwd
          echo "== Directory Tree =="
          find . -name "*.py"

      - name: Run feature pipeline and load to Hopsworks
        run: |
          echo "== Setting PYTHONPATH to project root =="
          export PYTHONPATH=$(pwd)
          echo "PYTHONPATH=$PYTHONPATH"
          echo "== Running pipeline =="
          python -m pipelines.feature_pipeline
        env:
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
