name: citibike_rides_hourly_features_pipeline

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch: {}

jobs:
  run-feature-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_feature_pipeline.txt

      - name: Debug environment
        run: |
          echo "== PWD =="
          pwd
          echo "== Directory Tree =="
          find . -name "*.py"

      - name: Run feature pipeline directly (script mode)
        env:
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
        run: |
          echo "== Running pipelines/feature_pipeline.py directly =="
          python pipelines/feature_pipeline.py
